ARCHS = armv7 arm64
TARGET = iphone:clang::
include ../theos/makefiles/common.mk

BUNDLE_NAME = PFSRespring
PFSRespring_FILES = Switch.xm
PFSRespring_FRAMEWORKS = UIKit
PFSRespring_LIBRARIES = flipswitch
PFSRespring_INSTALL_PATH = /Library/Switches

include ../theos/makefiles/bundle.mk
